baseURL = "http://ezwebcraft.com/"
languageCode = "en-us"
title = "EZ-WebCraft"
theme = "ananke"
#theme = "hyde-hyde"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "I am a Linux engineer by day and a Developer by night"
  twitter = "https://twitter.com/PatchCat13?lang=en"
  github = "https://github.com/ezwebcraft"
  linkedin = "https://www.linkedin.com/in/ramirez2017"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/bg1.jpg"
  recent_posts_number = 5
