baseURL = "https://linuxbytes.github.io"
languageCode = "en-us"
title = "linuxbytes"
theme = "hello-friend"


[params]
  subtitle = "I am a Linux engineer by day and a Coder by night"

[params.logo]
  logoText = "Linux Bytes"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "Archives"
    name = "Archives"
    url = "archives/"
