baseURL = "http://ezwebcraft.com/"
languageCode = "en-us"
title = "EZ-WebCraft"
theme = "hello-friend"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "I am a Linux engineer by day and a Developer by night"
  twitter = "https://twitter.com/PatchCat13?lang=en"
  github = "https://github.com/ezwebcraft"
  linkedin = "https://www.linkedin.com/in/ramirez2017"
  recent_posts_number = 5
  subtitle = "I am a Linux engineer by day and a Developer by night"
  logoText = "EZ WebCraft"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
